import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Pricing from "../src/views/pricing";

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Pricing Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Pricing />
    </React.Fragment>
  );
};

export default Home;
